/hik_camera:
  ros__parameters:
    camera_name: narrow_stereo
    exposure_time: 6000
    gain: 32.0

/auto_aim_detector_node:
  ros__parameters:
    debug: true
    use_fusion_detector: true
    set_enemy_color: 1
    show_time_cost: true
    Machine:
      pic_min_threshold: 0.0
    ArmorFinder:
      armor_min_height_ratio: 0.2
      small_armor_min_aspect_ratio: 0.8
      small_armor_max_aspect_ratio: 3.2
      big_armor_min_aspect_ratio: 3.2
      big_armor_max_aspect_ratio: 8.0
      max_center_angle: 25.0
    YoloModel:
      yolo_model_path: "/home/luis/workshop_ws/src/auto_aim/models/yolo.onnx"
    NumberFinder:
      number_model_path: "/home/luis/workshop_ws/src/auto_aim/models/fc2.onnx"

/auto_aim_processor_node:
  ros__parameters:
    debug: true
    Coordinate:
      intrinsic: [2370.573108953692, 0.0, 711.1306749974372, 0.0, 2370.263325810751, 571.3160085742733, 0.0, 0.0, 1.0]
      distcoeffs: [-0.08590936981698154, 1.171532639048541, -0.001884908679011257, -0.0031928983215215, -5.942126178608666]
      shaft_differ_x: 0.0
      shaft_differ_y: -4.59
      shaft_differ_z: 12.282
      sot_shaft_differ_x: 0.0
      sot_shaft_differ_y: -4.66
      sot_shaft_differ_z: 12.371
      sot_shifting_yaw: -1.35
      sot_shifting_pitch: 0.4
    bullet_speed: 2330.0

/serial_send_data_node:
  ros__parameters:
    debug: false
    close_shoot: false
    negation_send_yaw: true
    negation_send_pitch: true

/serial_read_data_node:
  ros__parameters:
    debug: false
    negation_read_yaw: true
    negation_read_pitch: true

/auto_aim_debug_node:
  ros__parameters:
    show: true
    show_detect: true
    show_process: false
    show_time_cost: false
    use_sensor_data_qos: false
    open_origin_image_loader: false
    open_show_image_loader: true
    load_video_root_path: "src/auto_aim_debug/debug_videos"
    recording_time: -1.0
    avi: false
    image_width: 1440
    image_height: 1080
